package scanner.classes;

public enum Type {
    RESERVED_KEYWORD,
    IDENTIFIER,
    INTEGER_NUMBER,
    REAL_NUMBER,
    BOOLEAN,
    HEX,
    SCIENTIFIC_NOTATION,
    STRING,
    ESCAPE_CHAR,
    COMMENT,
    OPERATOR_AND_PUNCTUATION,
    WHITESPACE,
    UNDEFINED,
    INT_ARRAY,
    BOOL_ARRAY,
    STRING_ARRAY,
    DOUBLE_ARRAY
}
